import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";
import ClientLayout from "./layout/ClientLayout";
import { NextIntlClientProvider } from "next-intl";
import { redirect, routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import ReduxProvider from "@/provider/ReduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const locale = (await params).locale;

  if (!routing.locales.includes(locale)) {
    return redirect("/not-found");
  }

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
        <NextIntlClientProvider messages={messages}>
          <div className="">
            <ClientLayout>{children}</ClientLayout>
          </div>
        </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
